[package]
name = "runtime-ops"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
runtime-event-loop = { path = "../runtime-event-loop" }
runtime-permission = { path = "../runtime-permission" }
runtime-resource = { path = "../runtime-resource" }

[lints]
workspace = true

