[package]
name = "zintl-ui-view"
edition = "2024"
description.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
zintl-ui-render.workspace = true
