[package]
name = "zintl-deno"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
deno_ast = { version = "=0.53.1", features = ["transpiling"] }
deno_core = { path = "../../thirdparty/deno/libs/core" }
deno_error = "=0.7.1"
deno_runtime = { path = "../../thirdparty/deno/runtime", features = ["include_js_files_for_snapshotting", "only_snapshotted_js_sources"] }
deno_resolver = { path = "../../thirdparty/deno/libs/resolver" }
sys_traits = { version = "=0.1.27", features = ["real"] }

[build-dependencies]
deno_core = { path = "../../thirdparty/deno/libs/core" }
deno_runtime = { path = "../../thirdparty/deno/runtime", features = ["include_js_files_for_snapshotting", "snapshot"] }
