[package]
name = "zpd-appkit"
edition = "2024"
version.workspace = true
license.workspace = true
[features]
wgpu = []

[dependencies]
zpd-objc = { path = "../zpd-objc" }

[[test]]
name = "native"
path = "tests/native.rs"
harness = false

[[test]]
name = "sidebar"
path = "tests/sidebar.rs"
harness = false
