[workspace]
resolver = "3"
members = [
    "crates/runtime-engine",
    "crates/runtime-jsc",
    "crates/runtime-v8",
    "crates/zintl-host",
    "examples/javascript-repl",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.dependencies]
messageloop-core = { path = "../common/messageloop/messageloop-core" }
messageloop-io = { path = "../common/messageloop/messageloop-io" }
zintl-io-mounts = { path = "../io/zintl-io-mounts" }
