[package]
name = "runtime-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reactor-api = { path = "../reactor-api" }
runtime-event-loop = { path = "../runtime-event-loop" }
runtime-ops = { path = "../runtime-ops" }
runtime-permission = { path = "../runtime-permission" }
runtime-resource = { path = "../runtime-resource" }

[lints]
workspace = true

