[package]
name = "runtime-filesystem"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
runtime-event-loop = { path = "../runtime-event-loop" }
runtime-resource = { path = "../runtime-resource" }
rustix.workspace = true
unicode-normalization.workspace = true

[lints]
workspace = true
