[package]
name = "zintl-deno"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
deno_ast = { version = "=0.53.3", features = ["transpiling"] }
deno_core = { path = "../../thirdparty/deno/libs/core" }
deno_error = "=0.7.1"
deno_runtime = { path = "../../thirdparty/deno/runtime" }
deno_resolver = { path = "../../thirdparty/deno/libs/resolver" }
serde = { version = "1", features = ["derive"] }
sys_traits = { version = "=0.1.28", features = ["real"] }

[build-dependencies]
deno_core = { path = "../../thirdparty/deno/libs/core" }
deno_runtime = { path = "../../thirdparty/deno/runtime", features = ["snapshot"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
