[workspace]
resolver = "3"
members = [
    "messageloop-core",
    "messageloop-appkit",
    "messageloop-sync",
    "messageloop-io",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
