[package]
name = "zintl-run"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
zintl-ui.workspace = true
zintl-render.workspace = true
zintl-render-math.workspace = true
zintl-wgpu.workspace = true
winit = "0.30"
pollster = "0.3"
