[package]
name = "zintl-render-math"
edition = "2024"
description.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
bytemuck.workspace = true
cgmath.workspace = true
paste = "1.0"
