[package]
name = "javascript-repl"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
runtime-embed = { path = "../../crates/runtime-embed" }
runtime-engine = { path = "../../crates/runtime-engine" }
runtime-jsc = { path = "../../crates/runtime-jsc" }

[lints]
workspace = true
