[package]
name = "javascript-repl"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
boa_engine = { version = "0.20", default-features = false }
boa_gc = "0.20"
runtime-embed = { path = "../../crates/runtime-embed" }

[lints]
workspace = true
