[package]
name = "zintl-render"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[features]
wgpu = []
default = ["wgpu"]

[dependencies]
zintl-ui.workspace = true
zintl-render-math.workspace = true
bytemuck.workspace = true
ab_glyph = "0.2.29"
cgmath.workspace = true
