[package]
name = "zintl-render"
version = "0.1.0"
edition = "2024"

[dependencies]
zintl.workspace = true
winit = "0.30"
wgpu = "25"
pollster = "0.3"
font-kit = "0.14"
pathfinder_geometry = "0.5"
cgmath = "0.18"
bytemuck = "1.23"
