[package]
name = "zintl"
edition = "2024"
authors.workspace = true
version.workspace = true

[dependencies]
zintl-ui.workspace = true
zintl-render.workspace = true
zintl-widget.workspace = true
zintl-run.workspace = true
